### ISSUE TITLE
build_reflex returns "undefined method new"

### ISSUE THREAD

**Issue by LukeClancy** [podia/stimulus_reflex_testing#12]
Just started out trying to make some tests, and came across an error I cant seem to pin down. When calling build_reflex I get the error below. I am relatively new to rspec, so if its something unrelated, my bad.

## Steps taken

- looked into issues with the url, counted that out as my other non-reflex tests are working 
- attempted with multiple different urls (which have reflexes)
- made sure the url comes back with :success in a seperate test
- reflex is working on that page outside of testing

## Could it be...

in [test_case.rb](https://github.com/podia/stimulus_reflex_testing/blob/main/lib/stimulus_reflex/test_case.rb) there is an empty function which is called (reflex_class). Unless there is some inheritance functionality going on, that seems strange. 

## Spec

```
RSpec.describe 'Votable Test', type: :reflex, deving: true do
    let!(:category){ 
        user = make_user
        Community.create_with_category({title: "test1"}, {creator_id: user.id})
    }
    let!(:post){
        user = make_user
        Post.create({categories: [Category.first], title: "yo", text: "my", user_id: user.id})
    }
    let(:reflex) { 
        byebug
        build_reflex(url: posts_url)                         #  <--- error happens here
    }
    it 'likes' do
        @user = make_user; sign_in(@user);
        reflex.element.id = post.hgid(tag: 'like')
        reflex = reflex.run(:like)
        expect(reflex).to broadcast( :morph )

        post.reload
        expect(post.votes_for_count).to eq(1)
    end

```
## Stack Trace

```
Failure/Error: build_reflex(url: posts_url )
     
     NoMethodError:
       undefined method `new' for nil:NilClass
     # /var/lib/gems/2.7.0/gems/stimulus_reflex_testing-0.3.0/lib/stimulus_reflex/test_case.rb:34:in `build_reflex'
     # ./spec/spec.rb:283:in `block (2 levels) in <top (required)>'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:317:in `block (2 levels) in let'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:157:in `block (3 levels) in fetch_or_store'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:157:in `fetch'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:157:in `block (2 levels) in fetch_or_store'
     # /var/lib/gems/2.7.0/gems/rspec-support-3.10.2/lib/rspec/support/reentrant_mutex.rb:23:in `synchronize'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:156:in `block in fetch_or_store'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:155:in `fetch'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:155:in `fetch_or_store'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:317:in `block in let'
     # ./spec/spec.rb:287:in `block (2 levels) in <top (required)>'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
     # /var/lib/gems/2.7.0/gems/rspec-rails-4.0.2/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /var/lib/gems/2.7.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
     # /usr/local/bin/rspec:23:in `load'
     # /usr/local/bin/rspec:23:in `<main>'

```

**Comment by erlingur** [comment]
Did you ever figure this out? Hitting this same error.

**Comment by LukeClancy** [comment]
Sorry for the late reply - I didn't figure this out and have not done stimulus reflex testing. I figured I probably wouldn't of done JavaScript testing either had I used a different framework, so I am justifying it that way

**Comment by jasoncharnes** [comment]
I'm sorry you both ran into this. If you happen to run into this issue again (or are willing to try it out for fun) I removed the empty `reflex_class` method, as it seems to still work without it. I haven't released it to ruby gems but it is in `main` if you wanted to point your Gemfile to this repo to try it out.
