### ISSUE TITLE
build_reflex.run does not call before_reflex

### ISSUE THREAD

**Issue by ineluki00** [podia/stimulus_reflex_testing#13]
Hi,

I have the following reflex class:

```notification_reflex.rb
# frozen_string_literal: true

class NotificationReflex < ApplicationReflex
  before_reflex :set_notification_subscription, only: %i[toggle_state]

  def toggle_state
    next_state = @notification_subscription.read? ? :unread : :read
    @notification_subscription.update(state: next_state)
    morph :nothing
  end
  
  private

  def set_notification_subscription
    byebug
  end
```

that i want to test with the following:

```rb
require 'rails_helper'

RSpec.describe NotificationReflex, type: :reflex do
  describe '#toggle_state' do
    context 'if unauthenticated' do
      it 'raise UnauthorizedError' do
        reflex = build_reflex
        subject = reflex.run(:toggle_state)
        expect(subject).to raise_error(UnauthorizedError)
      end
    end
```

which gives me this result:

```sh
1) NotificationReflex#toggle_state if unauthenticated raise UnauthorizedError
     Failure/Error: next_state = @notification_subscription.read? ? :unread : :read
     
     NoMethodError:
       undefined method `read?' for nil:NilClass
     # ./app/reflexes/notification_reflex.rb:11:in `toggle_state'
     # /home/ineluki/.rvm/gems/ruby-3.0.1/gems/stimulus_reflex-3.4.1/lib/stimulus_reflex/reflex.rb:111:in `public_send'
     # /home/ineluki/.rvm/gems/ruby-3.0.1/gems/stimulus_reflex-3.4.1/lib/stimulus_reflex/reflex.rb:111:in `block in process'
     # /home/ineluki/.rvm/gems/ruby-3.0.1/gems/stimulus_reflex-3.4.1/lib/stimulus_reflex/reflex.rb:110:in `process'
     # /home/ineluki/.rvm/gems/ruby-3.0.1/gems/stimulus_reflex_testing-0.3.0/lib/stimulus_reflex/test_reflex_patches.rb:7:in `run'
     # ./spec/reflexes/notification_reflex_spec.rb:10:in `block (4 levels) in <top (required)>'
```

As you can see, the before_reflex :set_notification_subscription method is never called...

Stimulus Reflex: v3.4.1
Rails: 6.1.4
Ruby: 3.0.1

**Comment by jasoncharnes** [comment]
Sorry for the late reply! I am able to replicate this. Interestingly if I remove the `only:` argument running the tests gets me to the before action.

I will see if I can figure out what's causing the issue and get a fix out.
